const DATE_FORMAT = 'dd-LL-yyyy';
const ORDERS_HISTORY_PATH = 'orders_history.yml';
const ORDERS_HISTORY_DATE_FORMAT = 'dd-LL-yyyy';
const FILE_ENCODING = 'utf-8';

module.exports = {
  DATE_FORMAT: DATE_FORMAT,
  ORDERS_HISTORY_PATH: ORDERS_HISTORY_PATH,
  ORDERS_HISTORY_DATE_FORMAT: ORDERS_HISTORY_DATE_FORMAT,
  FILE_ENCODING: FILE_ENCODING
};